### ISSUE TITLE
license violation

### ISSUE THREAD

**Issue by crepererum** [CamDavidsonPilon/tdigest#34]
Recently, `tdigest` started to use `accumulation_tree` to accelerate lookups. Sadly, `accumulation_tree` is licensed under GPL3+ (as per [setup.py](https://github.com/tkluck/accumulation_tree/blob/master/setup.py#L23)), which means that `tdigest` [may not be able to use the MIT license](https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility). Also, projects using `tdigest` will automatically fall under GPL3 license as well.

**Comment by CamDavidsonPilon** [comment]
huh interesting - I totally missed this. Let me ask @tkluck how he feels about this.

**Comment by tkluck** [comment]
Will relicense. I do have to double-check that some of the code I've forked is MIT compatible. Thanks for raising the concern!

**Comment by tkluck** [comment]
Just released v0.5 under MIT licence: https://github.com/tkluck/accumulation_tree/releases/tag/v0.5 and also on PyPI.

Thanks again for flagging @crepererum ! I think this issue can be closed.

**Comment by crepererum** [comment]
Awesome. Thank you so much for the very quick and positive response 🙂
