### ISSUE TITLE
0.5.1.0 sdist is missing on PyPi

### ISSUE THREAD

**Issue by crepererum** [CamDavidsonPilon/tdigest#36]
0.5.1.0 sdist is missing on PyPi, as well python2 wheels.

**Comment by CamDavidsonPilon** [comment]
Thanks for letting me know:

I uploaded the py2 wheels just now, and the sdist: https://pypi.python.org/pypi/tdigest/0.5.1.0


Thanks! TIL about sdist and py2 vs py3.
